on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Install required dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg2 expect
      - name: Publish artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publish
      - name: Send email notification on failure
        if: failure()
        uses: dawidd6