on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install required dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg2 expect
      - name: Test
        run: ./gradlew test
      - name: Publish artifacts
        run:  ./gradlew publish jreleaserFullRelease