on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup OS
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg2 expect

      - name: Test
        run: ./gradlew test
