on:
  push:
    branches:
      - main
    paths:
      - lib/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup OS
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg2 expect

      - name: Test in Chrome
        env:
          BROWSER: chrome
        run: ./gradlew test

      - name: Test in Firefox
        env:
          BROWSER: firefox
        run: ./gradlew test -rerun-tasks
